dependency and docker base image updates
Senzing/entity-search-web-app pull request #176
Opened 2021-07-27 01:00 UTC by arawinters

# Pull request questions

## Which issue does this address

resolves #173 

## Why was change needed

security updates

## What does change improve

security

## packages updated:

- "@senzing/rest-api-client-ng": "^2.2.2"
- "@senzing/sdk-components-ng": "^2.2.3"
- "@senzing/sdk-graph-components": "^2.2.0"
- "ssri":"6.0.2"
- "url-parse":"1.5.1"
- "ng-packagr":"10.1.1"
- "lodash":"4.17.21"
- "jspdf":"2.3.1"
- "browserlist":"4.16.6"
- "dns-packet":"1.3.4"

2021-07-27 01:11 UTC, arawinters commented
so funny enough @roncewind I tried running `sudo docker scan senzing/entity-search-web-app:latest` and the command isn't available in linux as best I can figure. looks like it's only a Windows/Mac Desktop thing( https://docs.docker.com/engine/scan/#prerequisites )

it would still be _prudent_ to check that the fixes in this commit pass your criteria _**before**_ it goes to master but last time I installed docker on my windows machine it hosed sooOooo many things. If you want to you can check out the `branch->build->scan` with the following:

`git clone -b issue173.awinters.5 https://github.com/Senzing/entity-search-web-app.git`
`cd entity-search-web-app && docker build --tag senzing/entity-search-web-app .`
`docker scan senzing/entity-search-web-app:latest`

2021-07-27 01:34 UTC, docktermj approved these changes

2021-07-27 14:00 UTC, roncewind requested changes
Hey Are,  Looks like Mecurial is still introducing the vulnerability.
```✗ Critical severity vulnerability found in python2.7/libpython2.7-stdlib
  Description: Buffer Overflow
  Info: https://snyk.io/vuln/SNYK-DEBIAN10-PYTHON27-1063178
  Introduced through: mercurial@4.8.2-1+deb10u1
  From: mercurial@4.8.2-1+deb10u1 > python-defaults/python@2.7.16-1 > python-defaults/libpython-stdlib@2.7.16-1 > python2.7/libpython2.7-stdlib@2.7.16-2+deb10u1
  From: mercurial@4.8.2-1+deb10u1 > python-defaults/python@2.7.16-1 > python2.7@2.7.16-2+deb10u1 > python2.7/libpython2.7-stdlib@2.7.16-2+deb10u1
  From: mercurial@4.8.2-1+deb10u1 > python-defaults/python@2.7.16-1 > python-defaults/libpython-stdlib@2.7.16-1 > python-defaults/libpython2-stdlib@2.7.16-1 > python2.7/libpython2.7-stdlib@2.7.16-2+deb10u1
  and 7 more...```
  
  thanks.

2021-07-28 18:21 UTC, arawinters commented
> Hey @arawinters we should probably update the base image in the Makefile too. thanks!

2021-07-28 18:23 UTC, roncewind approved these changes

2021-07-28 18:24 UTC, merged